Repository discord-php/DiscordPHP, pull requests merged in 2022-01, with the labels that each got.

#662 Fix 32 bit GMP
  src/Discord/Discord.php
  src/Discord/Helpers/Bitwise.php
  src/Discord/Parts/Permissions/ChannelPermission.php
  src/Discord/Parts/Permissions/Permission.php
  src/Discord/Parts/Permissions/RolePermission.php
Labels: important

#664 Fix Emoji Event
  src/Discord/WebSockets/Events/GuildEmojiUpdate.php
  src/Discord/WebSockets/Events/GuildEmojisUpdate.php
Labels: bug

#672 Add missing Part attributes & Fix Welcome Screen bug
  src/Discord/Parts/Channel/Channel.php
  src/Discord/Parts/Channel/Message.php
  src/Discord/Parts/Embed/Author.php
  src/Discord/Parts/Embed/Footer.php
  src/Discord/Parts/Embed/Image.php
  src/Discord/Parts/Embed/Video.php
  src/Discord/Parts/Guild/Guild.php
  src/Discord/Parts/Guild/Invite.php
  src/Discord/Parts/OAuth/Application.php
  src/Discord/Parts/User/User.php
Labels: bug

#675 Fix permission errors
  V7_CONVERSION.md
  src/Discord/Helpers/Bitwise.php
  src/Discord/Parts/Channel/Message.php
  src/Discord/Parts/Guild/GuildTemplate.php
  src/Discord/Parts/Guild/ScheduledEvent.php
  src/Discord/Parts/Guild/Sticker.php
  src/Discord/Parts/Guild/WelcomeChannel.php
  src/Discord/Parts/Guild/WelcomeScreen.php
  src/Discord/Parts/Interactions/Command/Command.php
  src/Discord/Parts/Interactions/Command/Option.php
  src/Discord/Parts/Interactions/Interaction.php
  src/Discord/Parts/Interactions/Request/Resolved.php
  src/Discord/Parts/Permissions/ChannelPermission.php
  src/Discord/Parts/Permissions/Permission.php
  src/Discord/Parts/Permissions/RolePermission.php
Labels: bug, important

#678 Fix repository cleanup on refresh
  src/Discord/Repository/AbstractRepository.php
  src/Discord/Repository/Guild/ScheduledEventRepository.php
Labels: bug, important
